---
title: "1D vs. 2D Piecewise Smoothing"
author: "Isolde Lane Shaw"
date: "3/10/2022"
output: html_document
---

# SETUP
```{r setup, include=FALSE} 



knitr::opts_chunk$set(echo = TRUE)

#library(rgdal)
library(terra)
library(SpaDES)
library(data.table)
library(ggplot2) 
library(readr)
library(reshape2)
library(scales)
library(tidyr)
library(RColorBrewer)
library(dplyr)
library(forcats)
library(hrbrthemes)
library(viridis)
library(naniar)
#library(raster)
library(rasterVis)
library(ggh4x)
library(egg)
library(cowplot)

options(digits=3) #limit number of digits displayed

birdList <- sort(c("ALFL", "AMGO", "AMRO", "BARS", "BBWA", "BCCH", "BHCO", "BOCH", 
                   "BRBL", "BRCR", "CCSP", "CEDW", "CHSP", "CLSW", "CMWA", "COYE",
                   "DEJU", "GCKI", "GRAJ", "HETH", "HOWR", "LEFL", "MOWA", "OVEN",
                   "PAWA", "RBNU", "RCKI", "REVI", "SWTH", "TEWA", "YRWA"))
#dev.new()
cbPalette <- c( "#56B4E9",  "#0072B2","#009E73", "#F0E442","#E69F00","#D55E00", "#CC79A7", "#999999","black")

coloursViridis <- viridis(12, option = "E")
coloursFor <- coloursViridis[1:6]
coloursLand <- coloursViridis[7:12]
coloursAge <- coloursViridis[7]
colours1D2D <- coloursViridis[c(10,3)]
colours2D <- coloursViridis[3]


outputsDir <- checkPath("../../outputs", create = TRUE)
inputsDir <- checkPath("../../inputs", create = TRUE)
rasterToMatchLocation <- file.path(inputsDir, "LCC2005_V1_4a.tif")
### STUDY AREA ONE DETAILS
studyAreaLocation <- checkPath(file.path(inputsDir, "studyArea/studyArea_AB_BCR6/studyArea_AB_BCR6.shp"))
forClassRasterLocation <- checkPath(file.path(inputsDir, "forestClassRasters/vegTypesRas_AB_BCR6_2011"), create = TRUE)
ageRasterLocation <- checkPath(file.path(inputsDir, "forestClassRasters/ageRas_AB_BCR6_2011"), create = TRUE)
landClassRasterLocation <- checkPath(file.path(inputsDir, "forestClassRasters/landCoverRas_AB_BCR6_2010"), create = TRUE)

.studyAreaName <- "studyArea_AB_BCR6.shp"



```

# COMPARING 1D AND 2D POST-HOC BINNING

#ONE STUDY AREA

### proportions of classes unimodal

```{r paired t-test of unimodality}
 #Test if there is a difference in proportion of classes unimodal per bird using 1D vs 2D binning


#get data tables needed
assumptionsByClass1D <- as.data.table(read_csv(paste(outputsDir, "/outputBirdPreds/assumptionsByClass1D.csv", sep = "")))
names(assumptionsByClass1D)[names(assumptionsByClass1D) == 'landForClass'] <- 'landAgeClass'
assumptionsByClass1D <- assumptionsByClass1D[1:6]
assumptionsByClass1D  <- droplevels(assumptionsByClass1D)
# assumptionsByClass1D_land <- assumptionsByClass1D[1:6]
# assumptionsByClass1D_land  <- droplevels(assumptionsByClass1D_land)



assumptionsByClass2D <- as.data.frame(read_csv(paste(outputsDir, "/outputBirdPreds/assumptionsByClass2D.csv", sep = "")))


assumptionsByClass <- rbind(assumptionsByClass1D, assumptionsByClass2D)
assumptionsByClass <- assumptionsByClass[,2:6]
assumptionsByClass$smoothingType <- as.factor(assumptionsByClass$smoothingType)
assumptionsByClass$landAgeClass <- as.factor(assumptionsByClass$landAgeClass)

# assumptionsbyBirdTTestUnimodal <- cbind(assumptionsByClass[,c(1,4)], assumptionsByBird2D[,4])
#  colnames(assumptionsbyBirdTTestUnimodal) <- c( "birdSp","propUnimodal1D", "propUnimodal2D")
#  diffUniModal <- assumptionsbyBirdTTestUnimodal$propUnimodal1D - assumptionsbyBirdTTestUnimodal$propUnimodal2D
# hist(diffUniModal,   
#      col="darkblue", 
#      main="Histogram of differences between 1D and 2D proportion of classes unimodal by bird",
#      xlab="Difference")
# assumptionsbyBird %>%
#   group_by(binningType) %>%
#   get_summary_stats(propClassesUnimodal, type = "mean_sd")



#1D vs 2D 

print("1D vs 2D BC")
unimodalityTTest <- t.test(propBirdsUnimodal ~ smoothingType, 
                           data = assumptionsByClass)
unimodalityTTest



#  #Test if there is a difference in proportion of classes normal per bird using 1D vs 2D binning
# assumptionsbyBirdTTestNormal <- cbind(assumptionsByBird1DFor[,c(1,3)], assumptionsByBird2D[,3])
#  colnames(assumptionsbyBirdTTestNormal) <- c( "birdSp","propNormal1D", "propNormal2D")
#  diffNormal <- assumptionsbyBirdTTestNormal$propNormal1D - assumptionsbyBirdTTestNormal$propNormal2D
# hist(diffNormal,   
#      col="darkblue", 
#      main="Histogram of differences between 1D and 2D proportion of classes unimodal by bird",
#      xlab="Difference")
# assumptionsbyBird %>%
#   group_by(binningType) %>%
#   get_summary_stats(propClassesNormal, type = "mean_sd")
# normalityTTest <- t.test(propClassesNormal ~ binningType, data = assumptionsbyBird, paired = TRUE)
# normalityTTest
```

## spearman stats
```{r paired t-test of correlation}

spearmanStats <- as.data.frame(read_csv(paste(outputsDir, "/outputBirdPreds/spearmanStats.csv", sep = "")))
names(spearmanStats) <- c("birdSp", "spearman1D", "spearman2D")

#spearmanStats$ageClasses <- as.numeric(spearmanStats$ageClasses)

spearmanStats <- gather(data=spearmanStats, key="smoothingType", value="spearmanStat",  -birdSp)
#spearmanStats <- unite(spearmanStats, dataset, c(binningType, ageClasses), remove=FALSE)
spearmanStats <-na.omit(spearmanStats)
spearmanStats <- as.data.table(spearmanStats)


#1D vs 2D 

print("1D vs 2D")
corrTTest <- t.test(spearmanStat ~ smoothingType,
                    data = spearmanStats)
corrTTest



```

## morans I
```{r paired t-test of spatauto}

resStats <- as.data.frame(read_csv(paste(outputsDir, "/outputBirdPreds/resStats.csv", sep = "")))
names(resStats) <- c("birdSp", "medianRes1D", "medianRes2D","moran1D", "moran2D")

moranStats <- resStats[,c(1,4:5)]

moranStats <- gather(data=moranStats, key="smoothingType", value="MoransI", -birdSp)

moranStats <-na.omit(moranStats)
moranStats <- as.data.table(moranStats)


#1D vs 2D

print("1D vs 2D Moran")
saTTest <- t.test(MoransI ~ smoothingType, 
                     data = moranStats)
saTTest



```

#TWO STUDY AREAS

### proportions of classes unimodal


```{r paired t-test of unimodality}
 #Test if there is a difference in proportion of classes unimodal per bird using 1D vs 2D binning

#get data tables needed
assumptionsByClass1D_1 <- as.data.table(read_csv("Results/PS results AB 20 yr age classes boot ras/assumptionsByClass1D.csv"))
assumptionsByClass1D_1 <- assumptionsByClass1D_1[7:13]
assumptionsByClass1D_1  <- droplevels(assumptionsByClass1D_1)
studyArea <- rep("AB", each = nrow(assumptionsByClass1D_1))
ageClasses <- rep("20", each = nrow(assumptionsByClass1D_1))
assumptionsByClass1D_1 <- cbind(assumptionsByClass1D_1, studyArea, ageClasses)
names(assumptionsByClass1D_1)[names(assumptionsByClass1D_1) == 'uniqueClasses'] <- 'landAgeClass'

assumptionsByClass1D_2 <- as.data.table(read_csv("Results/PS results BC 20 yr age classes boot ras/assumptionsByClass1D.csv"))
assumptionsByClass1D_2 <- assumptionsByClass1D_2[7:13]
assumptionsByClass1D_2  <- droplevels(assumptionsByClass1D_2)
studyArea <- rep("BC", each = nrow(assumptionsByClass1D_2))
ageClasses <- rep("20", each = nrow(assumptionsByClass1D_2))
assumptionsByClass1D_2 <- cbind(assumptionsByClass1D_2, studyArea, ageClasses)
names(assumptionsByClass1D_2)[names(assumptionsByClass1D_2) == 'uniqueClasses'] <- 'landAgeClass'

# assumptionsByClass2D_1 <- as.data.frame(read_csv("Results/PS results AB 10 yr age classes boot ras/assumptionsByClass2D.csv"))
# studyArea <- rep("AB", each = nrow(assumptionsByClass2D_1))
# ageClasses <- rep("10", each = nrow(assumptionsByClass2D_1))
# assumptionsByClass2D_1 <- cbind(assumptionsByClass2D_1, studyArea, ageClasses)

assumptionsByClass2D_2 <- as.data.frame(read_csv("Results/PS results AB 20 yr age classes boot ras/assumptionsByClass2D.csv"))
studyArea <- rep("AB", each = nrow(assumptionsByClass2D_2))
ageClasses <- rep("20", each = nrow(assumptionsByClass2D_2))
assumptionsByClass2D_2 <- cbind(assumptionsByClass2D_2, studyArea, ageClasses)

# assumptionsByClass2D_3 <- as.data.frame(read_csv("Results/PS results BC 10 yr age classes boot ras/assumptionsByClass2D.csv"))
# studyArea <- rep("BC", each = nrow(assumptionsByClass2D_3))
# ageClasses <- rep("10", each = nrow(assumptionsByClass2D_3))
# assumptionsByClass2D_3 <- cbind(assumptionsByClass2D_3, studyArea, ageClasses)

assumptionsByClass2D_4 <- as.data.frame(read_csv("Results/PS results BC 20 yr age classes boot ras/assumptionsByClass2D.csv"))
studyArea <- rep("BC", each = nrow(assumptionsByClass2D_4))
ageClasses <- rep("20", each = nrow(assumptionsByClass2D_4))
assumptionsByClass2D_4 <- cbind(assumptionsByClass2D_4, studyArea, ageClasses)





# assumptionsbyBirdTTestUnimodal <- cbind(assumptionsByClass[,c(1,4)], assumptionsByBird2D[,4])
#  colnames(assumptionsbyBirdTTestUnimodal) <- c( "birdSp","propUnimodal1D", "propUnimodal2D")
#  diffUniModal <- assumptionsbyBirdTTestUnimodal$propUnimodal1D - assumptionsbyBirdTTestUnimodal$propUnimodal2D
# hist(diffUniModal,   
#      col="darkblue", 
#      main="Histogram of differences between 1D and 2D proportion of classes unimodal by bird",
#      xlab="Difference")
# assumptionsbyBird %>%
#   group_by(binningType) %>%
#   get_summary_stats(propClassesUnimodal, type = "mean_sd")



#1D vs 2D BC

assumptionsByClass <- rbind( assumptionsByClass1D_2, assumptionsByClass2D_4)
assumptionsByClass <- unite(assumptionsByClass, dataset, c(binningType, ageClasses), remove=FALSE)

print("1D vs 2D BC")
unimodalityTTest_BC <- t.test(propBirdsUnimodal ~ binningType, data = assumptionsByClass, paired = FALSE)
unimodalityTTest_BC

#1D vs 2D AB

assumptionsByClass <- rbind( assumptionsByClass1D_1, assumptionsByClass2D_2)
assumptionsByClass <- unite(assumptionsByClass, dataset, c(binningType, ageClasses), remove=FALSE)

print("1D vs 2D AB")
unimodalityTTest_AB <- t.test(propBirdsUnimodal ~ binningType, data = assumptionsByClass, paired = FALSE)
unimodalityTTest_AB

#BC vs AB 1D

assumptionsByClass <- rbind( assumptionsByClass1D_1, assumptionsByClass1D_2)
assumptionsByClass <- unite(assumptionsByClass, dataset, c(binningType, ageClasses), remove=FALSE)

print("BC vs AB 1D")
unimodalityTTest_1D <- t.test(propBirdsUnimodal ~ studyArea, data = assumptionsByClass, paired = TRUE)
unimodalityTTest_1D


#BC vs AB 2D

assumptionsByClass <- rbind( assumptionsByClass2D_2, assumptionsByClass2D_4)
assumptionsByClass <- unite(assumptionsByClass, dataset, c(binningType, ageClasses), remove=FALSE)

print("BC vs AB 2D")
unimodalityTTest_2D <- t.test(propBirdsUnimodal ~ studyArea, data = assumptionsByClass, paired = FALSE)
unimodalityTTest_2D

#  #Test if there is a difference in proportion of classes normal per bird using 1D vs 2D binning
# assumptionsbyBirdTTestNormal <- cbind(assumptionsByBird1DFor[,c(1,3)], assumptionsByBird2D[,3])
#  colnames(assumptionsbyBirdTTestNormal) <- c( "birdSp","propNormal1D", "propNormal2D")
#  diffNormal <- assumptionsbyBirdTTestNormal$propNormal1D - assumptionsbyBirdTTestNormal$propNormal2D
# hist(diffNormal,   
#      col="darkblue", 
#      main="Histogram of differences between 1D and 2D proportion of classes unimodal by bird",
#      xlab="Difference")
# assumptionsbyBird %>%
#   group_by(binningType) %>%
#   get_summary_stats(propClassesNormal, type = "mean_sd")
# normalityTTest <- t.test(propClassesNormal ~ binningType, data = assumptionsbyBird, paired = TRUE)
# normalityTTest
```

## spearman stats
```{r paired t-test of correlation}

spearmanStats_AB20 <- as.data.frame(read_csv("Results/PS results AB 20 yr age classes boot ras/spearmanStats.csv"))
studyArea <- rep("AB", each = nrow(spearmanStats_AB20))
ageClasses <- rep("20", each = nrow(spearmanStats_AB20))
spearmanStats_AB20 <- cbind(spearmanStats_AB20, studyArea, ageClasses)

# spearmanStats_BC10 <- as.data.frame(read_csv("Results/PS results BC 10 yr age classes boot ras/spearmanStats.csv"))
# studyArea <- rep("BC", each = nrow(spearmanStats_BC10))
# ageClasses <- rep("10", each = nrow(spearmanStats_BC10))
# spearmanStats_BC10 <- cbind(spearmanStats_BC10, studyArea, ageClasses)
# spearmanStats_BC10[,2] <- NA

spearmanStats_BC20 <- as.data.frame(read_csv("Results/PS results BC 20 yr age classes boot ras/spearmanStats.csv"))
studyArea <- rep("BC", each = nrow(spearmanStats_BC20))
ageClasses <- rep("20", each = nrow(spearmanStats_BC20))
spearmanStats_BC20 <- cbind(spearmanStats_BC20, studyArea, ageClasses)

spearmanStats <- rbind( spearmanStats_AB20, spearmanStats_BC20)
names(spearmanStats)[names(spearmanStats) == '...1'] <- 'birdSp'
spearmanStats$ageClasses <- as.numeric(spearmanStats$ageClasses)

spearmanStats <- gather(data=spearmanStats, key="binningType", value="spearmanStat", -studyArea, -ageClasses, -birdSp)
spearmanStats <- unite(spearmanStats, dataset, c(binningType, ageClasses), remove=FALSE)
spearmanStats <-na.omit(spearmanStats)
spearmanStats <- as.data.table(spearmanStats)


#1D vs 2D BC

spearmanStatsBC <- spearmanStats[studyArea == "BC"]
spearmanStatsBC  <- droplevels(spearmanStatsBC)
print("1D vs 2D BC")
corrTTest_BC <- t.test(spearmanStat ~ binningType, data = spearmanStatsBC, paired = TRUE)
corrTTest_BC

#1D vs 2D AB

spearmanStatsAB <- spearmanStats[studyArea == "AB"]
spearmanStatsAB  <- droplevels(spearmanStatsAB)
print("1D vs 2D AB")
corrTTest_AB <- t.test(spearmanStat ~ binningType, data = spearmanStatsAB, paired = TRUE)
corrTTest_AB

#BC vs AB 1D
spearmanStats1D <- spearmanStats[binningType == "spearman1D"]
spearmanStats1D  <- droplevels(spearmanStats1D)
print("BC vs AB 1D")
corrTTest_1D <- t.test(spearmanStat ~ studyArea, data = spearmanStats1D, paired = FALSE)
corrTTest_1D


#BC vs AB 2D
spearmanStats2D <- spearmanStats[binningType == "spearman2D"]
spearmanStats2D  <- droplevels(spearmanStats2D)
print("BC vs AB 2D")
corrTTest_2D <- t.test(spearmanStat ~ studyArea, data = spearmanStats2D, paired = FALSE)
corrTTest_2D


```

## morans I
```{r paired t-test of spatauto}

resStats <- as.data.frame(read_csv("Results/PS results AB 20 yr age classes boot ras/resStats.csv"))
studyArea <- rep("AB", each = nrow(resStats_AB20))
ageClasses <- rep("20", each = nrow(resStats_AB20))
resStats_AB20 <- cbind(resStats_AB20, studyArea, ageClasses)
resStats_AB20 <- resStats_AB20[,c(1,4:7)]



resStats <- rbind( resStats_AB20,  resStats_BC20)
names(resStats)[names(resStats) == '...1'] <- 'birdSp'
resStats$ageClasses <- as.numeric(resStats$ageClasses)

autoCorStats <- gather(data=resStats, key="binningType", value="autocorStat", autocor1DRes, autocor2DRes, -studyArea, -ageClasses, -birdSp)
autoCorStats <- unite(autoCorStats, dataset, c(binningType, ageClasses), remove=FALSE)
autoCorStats <-na.omit(autoCorStats)
autoCorStats <- as.data.table(autoCorStats)


#1D vs 2D BC

autoCorStatsBC <- autoCorStats[studyArea == "BC"]
autoCorStatsBC  <- droplevels(autoCorStatsBC)
print("1D vs 2D BC")
saTTest_BC <- t.test(autocorStat ~ binningType, data = autoCorStatsBC, paired = TRUE)
saTTest_BC

#1D vs 2D AB

autoCorStatsAB <- autoCorStats[studyArea == "AB"]
autoCorStatsAB  <- droplevels(autoCorStatsAB)
print("1D vs 2D AB")
saTTest_AB <- t.test(autocorStat ~ binningType, data = autoCorStatsAB, paired = TRUE)
saTTest_AB

#BC vs AB 1D
autoCorStats1D <- autoCorStats[binningType == "autocor2DRes"]
autoCorStats1D  <- droplevels(autoCorStats1D)
print("BC vs AB 1D")
saTTest_1D <- t.test(autocorStat ~ studyArea, data = autoCorStats1D, paired = FALSE)
saTTest_1D


#BC vs AB 2D
autoCorStats2D <- autoCorStats[binningType == "autocor2DRes"]
autoCorStats2D  <- droplevels(autoCorStats2D)
print("BC vs AB 2D")
saTTest_2D <- t.test(autocorStat ~ studyArea, data = autoCorStats2D, paired = FALSE)
saTTest_2D


```
